name: ft-receipts
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_5
  - ca-certificates=2024.3.11=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.13=h7f8727e_0
  - pip=23.3.1=py311h06a4308_0
  - python=3.11.8=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py311h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - xz=5.4.6=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - accelerate==0.28.0
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - anyio==4.3.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - astor==0.8.1
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrdict==2.0.1
      - attrs==23.2.0
      - babel==2.14.0
      - backcall==0.2.0
      - bce-python-sdk==0.9.6
      - beautifulsoup4==4.12.3
      - bitsandbytes==0.43.0
      - bleach==6.1.0
      - blinker==1.7.0
      - blis==0.7.11
      - cachetools==5.3.3
      - catalogue==2.0.10
      - certifi==2024.2.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpathlib==0.16.0
      - comm==0.2.2
      - confection==0.1.4
      - contourpy==1.2.0
      - cssselect==1.2.0
      - cssutils==2.10.2
      - curated-tokenizers==0.0.9
      - curated-transformers==0.1.1
      - cycler==0.12.1
      - cymem==2.0.8
      - cython==3.0.10
      - datasets==2.18.0
      - debugpy==1.8.1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dill==0.3.8
      - diskcache==5.6.3
      - distro==1.9.0
      - docstring-parser==0.15
      - einops==0.7.0
      - en-core-web-trf==3.7.3
      - et-xmlfile==1.1.0
      - executing==2.0.1
      - fastapi==0.110.1
      - fastjsonschema==2.19.1
      - filelock==3.13.1
      - fire==0.6.0
      - flask==3.0.2
      - flask-babel==4.0.0
      - fonttools==4.50.0
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - future==1.0.0
      - h11==0.14.0
      - httpcore==1.0.4
      - httpx==0.27.0
      - huggingface-hub==0.21.4
      - idna==3.6
      - imageio==2.34.0
      - imgaug==0.4.0
      - instructor==1.0.3
      - ipykernel==6.29.3
      - ipython==7.34.0
      - ipywidgets==8.1.2
      - isoduration==20.11.0
      - itsdangerous==2.1.2
      - jedi==0.19.1
      - jinja2==3.1.3
      - json5==0.9.24
      - jsonpointer==2.4
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-autotime==1.1.0
      - jupyter-client==8.6.1
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.4
      - jupyter-server==2.13.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.1.5
      - jupyterlab-code-formatter==2.2.1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.25.4
      - jupyterlab-widgets==3.0.10
      - kiwisolver==1.4.5
      - lab==8.1
      - langcodes==3.3.0
      - lazy-loader==0.3
      - llama-cpp-python==0.2.60
      - lmdb==1.4.1
      - loralib==0.1.2
      - lxml==5.2.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.8.3
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - mistune==3.0.2
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - murmurhash==1.0.10
      - nbclient==0.10.0
      - nbconvert==7.16.2
      - nbformat==5.10.3
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - notebook==7.1.2
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.4.99
      - nvidia-nvtx-cu12==12.1.105
      - openai==1.16.2
      - opencv-contrib-python==4.6.0.66
      - opencv-python==4.6.0.66
      - opencv-python-headless==4.9.0.80
      - openpyxl==3.1.2
      - opt-einsum==3.3.0
      - overrides==7.7.0
      - packaging==24.0
      - paddleocr==2.7.3
      - paddlepaddle-gpu==2.6.1
      - pandas==2.2.1
      - pandocfilters==1.5.1
      - parso==0.8.3
      - pdf2docx==0.5.8
      - peft==0.9.0
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.2.0
      - platformdirs==4.2.0
      - premailer==3.10.0
      - preshed==3.0.9
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.43
      - protobuf==3.20.3
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==15.0.2
      - pyarrow-hotfix==0.6
      - pyclipper==1.3.0.post5
      - pycparser==2.21
      - pycryptodome==3.20.0
      - pydantic==2.7.0b1
      - pydantic-core==2.18.0
      - pydantic-settings==2.2.1
      - pygments==2.17.2
      - pymupdf==1.23.26
      - pymupdfb==1.23.22
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - python-docx==1.1.0
      - python-dotenv==1.0.1
      - python-json-logger==2.0.7
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==25.1.2
      - qtconsole==5.5.1
      - qtpy==2.4.1
      - rapidfuzz==3.7.0
      - rarfile==4.1
      - referencing==0.34.0
      - regex==2023.12.25
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.1
      - rpds-py==0.18.0
      - safetensors==0.4.2
      - scikit-image==0.22.0
      - scipy==1.12.0
      - send2trash==1.8.2
      - sentencepiece==0.2.0
      - shapely==2.0.3
      - shtab==1.7.1
      - simplejson==3.19.2
      - six==1.16.0
      - smart-open==6.4.0
      - sniffio==1.3.1
      - soupsieve==2.5
      - spacy==3.7.4
      - spacy-curated-transformers==0.2.2
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.4.8
      - sse-starlette==2.1.0
      - stack-data==0.6.3
      - starlette==0.37.2
      - starlette-context==0.3.6
      - sympy==1.12
      - tenacity==8.2.3
      - termcolor==2.4.0
      - terminado==0.18.1
      - thinc==8.2.3
      - tifffile==2024.2.12
      - tiktoken==0.6.0
      - tinycss2==1.2.1
      - tokenizers==0.15.2
      - torch==2.1.0
      - torchaudio==2.2.1
      - torchvision==0.17.1
      - tornado==6.4
      - tqdm==4.66.2
      - traitlets==5.14.2
      - transformers==4.39.3
      - triton==2.1.0
      - trl==0.8.1
      - txt2tags==3.9
      - typer==0.9.4
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.10.0
      - tyro==0.7.3
      - tzdata==2024.1
      - unsloth==2024.4
      - uri-template==1.3.0
      - urllib3==2.2.1
      - uvicorn==0.29.0
      - visualdl==2.5.3
      - wasabi==1.1.2
      - wcwidth==0.2.13
      - weasel==0.3.4
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - werkzeug==3.0.2
      - wheel==0.43.0
      - widgetsnbextension==4.0.10
      - wordcloud==1.9.3
      - xformers==0.0.22.post7
      - xxhash==3.4.1
      - yarl==1.9.4
      - youtube-transcript-api==0.6.2
prefix: /miniconda/envs/ft-receipts
